### ISSUE TITLE
Syntax not highlighted for `fastcgi_split_path_info` and `try_files`

### ISSUE THREAD

**Issue by brazenest-zz** [shanoor/vscode-nginx#4]
![syntaxhighlightingissue](https://user-images.githubusercontent.com/10803611/29337664-20d73cda-81e0-11e7-9954-4f233360a130.png)

Running v0.3.1, not sure why 7ad4584 didn't resolve the lack of highlighting for `fastcgi_split_path_info`

**Comment by shanoor** [comment]
Hi, `fastcgi_split_path_info` was already highlighted, I added `try_files` with the latest version (0.4.1).
